import type {
  CeremonyLayout,
  DinnerTable,
  ExportType,
  Guest,
  MusicCue,
  PreviewPhase,
  Speech,
  TimelineItem,
  VenueLayout,
  Wedding
} from "@/lib/wedding-types";

export const sampleWedding: Wedding = {
  id: "emma-james-2027",
  coupleNames: "Emma & James",
  partnerOneName: "Emma Carter",
  partnerTwoName: "James Bennett",
  date: "June 14, 2027",
  ceremonyLocation: "St. James Chapel",
  receptionLocation: "Rosewood Hall",
  guestCount: 112,
  style: "Editorial garden wedding, warm ivory, soft champagne, black tie optional, classic but modern",
  plannerName: "Olivia Hart",
  status: "Production map in progress"
};

export const coreTeam = [
  { role: "Couple", name: "Emma Carter and James Bennett" },
  { role: "Wedding planner", name: "Olivia Hart" },
  { role: "Toastmaster / MC", name: "Daniel Brooks" },
  { role: "Photographer", name: "Clara Hayes" },
  { role: "DJ", name: "Miles Reed" },
  { role: "Catering lead", name: "Sophia Grant" },
  { role: "Venue manager", name: "Henry Cole" },
  { role: "Officiant", name: "Reverend Thomas Allen" },
  { role: "Florist", name: "Violet & Stem Studio" }
];

export const ceremonyLayout: CeremonyLayout = {
  id: "st-james-chapel-layout",
  name: "St. James Chapel",
  rows: 18,
  seatsPerSidePerRow: 5,
  reservedFrontRows: 2,
  aisleType: "Center aisle",
  guestCount: 112,
  musicians: ["Organist", "Soloist"],
  photographerPositions: ["Left aisle", "Back center", "Balcony"],
  officiantName: "Reverend Thomas Allen"
};

export const guests: Guest[] = [
  {
    id: "emma-carter",
    name: "Emma Carter",
    household: "Couple",
    rsvpStatus: "attending",
    mealChoice: "Tasting menu",
    allergies: [],
    tags: ["couple"],
    relationship: "Partner one",
    accessibilityNotes: "",
    conflictGuestIds: [],
    preferredGuestIds: [],
    language: "English",
    tableId: "sweetheart-table",
    seatIndex: 0
  },
  {
    id: "james-bennett",
    name: "James Bennett",
    household: "Couple",
    rsvpStatus: "attending",
    mealChoice: "Tasting menu",
    allergies: [],
    tags: ["couple"],
    relationship: "Partner two",
    accessibilityNotes: "",
    conflictGuestIds: [],
    preferredGuestIds: [],
    language: "English",
    tableId: "sweetheart-table",
    seatIndex: 1
  },
  {
    id: "anna-carter",
    name: "Anna Carter",
    household: "Carter",
    rsvpStatus: "attending",
    mealChoice: "Chicken",
    allergies: ["Nut allergy"],
    tags: ["family", "accessible seating"],
    relationship: "Family",
    accessibilityNotes: "Seat close to the entrance with a clear route.",
    conflictGuestIds: [],
    preferredGuestIds: ["robert-carter"],
    language: "English",
    tableId: "table-1",
    seatIndex: 0
  },
  {
    id: "robert-carter",
    name: "Robert Carter",
    household: "Carter",
    rsvpStatus: "attending",
    mealChoice: "Beef",
    allergies: [],
    tags: ["family"],
    relationship: "Father of the bride",
    accessibilityNotes: "",
    conflictGuestIds: [],
    preferredGuestIds: ["anna-carter"],
    language: "English",
    tableId: "table-1",
    seatIndex: 1
  },
  {
    id: "margaret-bennett",
    name: "Margaret Bennett",
    household: "Bennett",
    rsvpStatus: "attending",
    mealChoice: "Fish",
    allergies: [],
    tags: ["family"],
    relationship: "Family",
    accessibilityNotes: "",
    conflictGuestIds: [],
    preferredGuestIds: ["charles-bennett"],
    language: "English",
    tableId: "table-1",
    seatIndex: 2
  },
  {
    id: "charles-bennett",
    name: "Charles Bennett",
    household: "Bennett",
    rsvpStatus: "attending",
    mealChoice: "Beef",
    allergies: [],
    tags: ["family"],
    relationship: "Family",
    accessibilityNotes: "",
    conflictGuestIds: [],
    preferredGuestIds: ["margaret-bennett"],
    language: "English",
    tableId: "table-1",
    seatIndex: 3
  },
  {
    id: "maria-holm",
    name: "Maria Holm",
    household: "Holm",
    rsvpStatus: "attending",
    mealChoice: "Fish",
    allergies: [],
    tags: ["family"],
    relationship: "Family friend",
    accessibilityNotes: "",
    conflictGuestIds: [],
    preferredGuestIds: ["thomas-holm"],
    language: "English",
    tableId: "table-1",
    seatIndex: 4
  },
  {
    id: "thomas-holm",
    name: "Thomas Holm",
    household: "Holm",
    rsvpStatus: "attending",
    mealChoice: "Beef",
    allergies: [],
    tags: ["family"],
    relationship: "Family friend",
    accessibilityNotes: "",
    conflictGuestIds: [],
    preferredGuestIds: ["maria-holm"],
    language: "English",
    tableId: "table-1",
    seatIndex: 5
  },
  {
    id: "daniel-brooks",
    name: "Daniel Brooks",
    household: "Brooks",
    rsvpStatus: "attending",
    mealChoice: "Beef",
    allergies: [],
    tags: ["Toastmaster"],
    relationship: "Friend",
    accessibilityNotes: "",
    conflictGuestIds: [],
    preferredGuestIds: [],
    language: "English",
    tableId: "table-2",
    seatIndex: 0
  },
  {
    id: "emily-ross",
    name: "Emily Ross",
    household: "Ross",
    rsvpStatus: "attending",
    mealChoice: "Chicken",
    allergies: [],
    tags: ["friend"],
    relationship: "Friend",
    accessibilityNotes: "",
    conflictGuestIds: [],
    preferredGuestIds: [],
    language: "English",
    tableId: "table-2",
    seatIndex: 1
  },
  {
    id: "michael-turner",
    name: "Michael Turner",
    household: "Turner",
    rsvpStatus: "attending",
    mealChoice: "Beef",
    allergies: [],
    tags: ["best man"],
    relationship: "Best man",
    accessibilityNotes: "",
    conflictGuestIds: [],
    preferredGuestIds: [],
    language: "English",
    tableId: "table-2",
    seatIndex: 2
  },
  {
    id: "sophie-lane",
    name: "Sophie Lane",
    household: "Lane",
    rsvpStatus: "attending",
    mealChoice: "Fish",
    allergies: [],
    tags: ["friend"],
    relationship: "Friend",
    accessibilityNotes: "",
    conflictGuestIds: [],
    preferredGuestIds: [],
    language: "English",
    tableId: "table-2",
    seatIndex: 3
  },
  {
    id: "erik-berg",
    name: "Erik Berg",
    household: "Berg",
    rsvpStatus: "attending",
    mealChoice: "Beef",
    allergies: [],
    tags: ["speech", "friend"],
    relationship: "College friend",
    accessibilityNotes: "",
    conflictGuestIds: [],
    preferredGuestIds: ["sofia-nilsson"],
    language: "English",
    tableId: "table-3",
    seatIndex: 0
  },
  {
    id: "sofia-nilsson",
    name: "Sofia Nilsson",
    household: "Nilsson",
    rsvpStatus: "attending",
    mealChoice: "Vegan",
    allergies: [],
    tags: ["vegan"],
    relationship: "College friend",
    accessibilityNotes: "",
    conflictGuestIds: [],
    preferredGuestIds: ["erik-berg"],
    language: "English",
    tableId: "table-3",
    seatIndex: 1
  },
  {
    id: "olivia-hart",
    name: "Olivia Hart",
    household: "Hart",
    rsvpStatus: "attending",
    mealChoice: "Chicken",
    allergies: [],
    tags: ["wedding planner"],
    relationship: "Planner",
    accessibilityNotes: "",
    conflictGuestIds: [],
    preferredGuestIds: [],
    language: "English",
    tableId: "table-3",
    seatIndex: 2
  },
  {
    id: "lucas-moore",
    name: "Lucas Moore",
    household: "Moore",
    rsvpStatus: "attending",
    mealChoice: "Fish",
    allergies: [],
    tags: ["friend"],
    relationship: "College friend",
    accessibilityNotes: "",
    conflictGuestIds: [],
    preferredGuestIds: [],
    language: "English",
    tableId: "table-3",
    seatIndex: 3
  },
  {
    id: "james-carter",
    name: "James Carter",
    household: "Carter",
    rsvpStatus: "attending",
    mealChoice: "Beef",
    allergies: [],
    tags: ["English-speaking", "international guest"],
    relationship: "International guest",
    accessibilityNotes: "",
    conflictGuestIds: [],
    preferredGuestIds: ["amelia-clarke"],
    language: "English",
    tableId: "table-4",
    seatIndex: 0
  },
  {
    id: "amelia-clarke",
    name: "Amelia Clarke",
    household: "Clarke",
    rsvpStatus: "attending",
    mealChoice: "Chicken",
    allergies: [],
    tags: ["English-speaking"],
    relationship: "International guest",
    accessibilityNotes: "",
    conflictGuestIds: [],
    preferredGuestIds: ["james-carter"],
    language: "English",
    tableId: "table-4",
    seatIndex: 1
  },
  {
    id: "oliver-smith",
    name: "Oliver Smith",
    household: "Smith",
    rsvpStatus: "attending",
    mealChoice: "Fish",
    allergies: [],
    tags: ["English-speaking"],
    relationship: "International guest",
    accessibilityNotes: "",
    conflictGuestIds: [],
    preferredGuestIds: [],
    language: "English",
    tableId: "table-4",
    seatIndex: 2
  },
  {
    id: "grace-wilson",
    name: "Grace Wilson",
    household: "Wilson",
    rsvpStatus: "attending",
    mealChoice: "Vegan",
    allergies: [],
    tags: ["English-speaking"],
    relationship: "International guest",
    accessibilityNotes: "",
    conflictGuestIds: [],
    preferredGuestIds: [],
    language: "English",
    tableId: "table-4",
    seatIndex: 3
  },
  {
    id: "clara-hayes",
    name: "Clara Hayes",
    household: "Hayes",
    rsvpStatus: "attending",
    mealChoice: "Chicken",
    allergies: [],
    tags: ["Photographer"],
    relationship: "Vendor",
    accessibilityNotes: "",
    conflictGuestIds: [],
    preferredGuestIds: ["noah-hayes", "lily-hayes"],
    language: "English",
    tableId: "table-5",
    seatIndex: 0
  },
  {
    id: "noah-hayes",
    name: "Noah Hayes",
    household: "Hayes",
    rsvpStatus: "attending",
    mealChoice: "Child meal",
    allergies: [],
    tags: ["child meal"],
    relationship: "Child",
    accessibilityNotes: "",
    conflictGuestIds: [],
    preferredGuestIds: ["clara-hayes"],
    language: "English",
    tableId: "table-5",
    seatIndex: 1
  },
  {
    id: "lily-hayes",
    name: "Lily Hayes",
    household: "Hayes",
    rsvpStatus: "attending",
    mealChoice: "Child meal",
    allergies: [],
    tags: ["child seat"],
    relationship: "Child",
    accessibilityNotes: "",
    conflictGuestIds: [],
    preferredGuestIds: ["clara-hayes"],
    language: "English",
    tableId: "table-5",
    seatIndex: 2
  },
  {
    id: "johan-ek",
    name: "Johan Ek",
    household: "Ek",
    rsvpStatus: "attending",
    mealChoice: "Beef",
    allergies: [],
    tags: ["conflict: avoid seating next to Lisa Ek"],
    relationship: "Work friend",
    accessibilityNotes: "",
    conflictGuestIds: ["lisa-ek"],
    preferredGuestIds: [],
    language: "English",
    tableId: "table-6",
    seatIndex: 0
  },
  {
    id: "lisa-ek",
    name: "Lisa Ek",
    household: "Ek",
    rsvpStatus: "attending",
    mealChoice: "Fish",
    allergies: [],
    tags: ["conflict: avoid seating next to Johan Ek"],
    relationship: "Work friend",
    accessibilityNotes: "",
    conflictGuestIds: ["johan-ek"],
    preferredGuestIds: [],
    language: "English",
    tableId: "table-6",
    seatIndex: 1
  },
  {
    id: "miles-reed",
    name: "Miles Reed",
    household: "Reed",
    rsvpStatus: "attending",
    mealChoice: "Chicken",
    allergies: [],
    tags: ["DJ"],
    relationship: "Vendor",
    accessibilityNotes: "",
    conflictGuestIds: [],
    preferredGuestIds: [],
    language: "English",
    tableId: "table-6",
    seatIndex: 2
  },
  {
    id: "sophia-grant",
    name: "Sophia Grant",
    household: "Grant",
    rsvpStatus: "attending",
    mealChoice: "Vegan",
    allergies: [],
    tags: ["Catering lead"],
    relationship: "Vendor",
    accessibilityNotes: "",
    conflictGuestIds: [],
    preferredGuestIds: [],
    language: "English",
    tableId: "table-6",
    seatIndex: 3
  }
];

export const dinnerTables: DinnerTable[] = [
  {
    id: "sweetheart-table",
    name: "Sweetheart Table",
    type: "Couple",
    shape: "sweetheart",
    capacity: 2,
    position: { x: 50, y: 20 },
    assignedGuestIds: ["emma-carter", "james-bennett"]
  },
  {
    id: "table-1",
    name: "Table 1 - Immediate Family",
    type: "Family",
    shape: "round",
    capacity: 10,
    position: { x: 24, y: 42 },
    assignedGuestIds: ["anna-carter", "robert-carter", "margaret-bennett", "charles-bennett", "maria-holm", "thomas-holm"]
  },
  {
    id: "table-2",
    name: "Table 2 - Friends",
    type: "Friends",
    shape: "round",
    capacity: 10,
    position: { x: 50, y: 46 },
    assignedGuestIds: ["daniel-brooks", "emily-ross", "michael-turner", "sophie-lane"]
  },
  {
    id: "table-3",
    name: "Table 3 - College Friends",
    type: "Friends",
    shape: "round",
    capacity: 10,
    position: { x: 76, y: 42 },
    assignedGuestIds: ["erik-berg", "sofia-nilsson", "olivia-hart", "lucas-moore"]
  },
  {
    id: "table-4",
    name: "Table 4 - International Guests",
    type: "International",
    shape: "round",
    capacity: 10,
    position: { x: 24, y: 70 },
    assignedGuestIds: ["james-carter", "amelia-clarke", "oliver-smith", "grace-wilson"]
  },
  {
    id: "table-5",
    name: "Table 5 - Family with Children",
    type: "Family",
    shape: "round",
    capacity: 10,
    position: { x: 50, y: 74 },
    assignedGuestIds: ["clara-hayes", "noah-hayes", "lily-hayes"]
  },
  {
    id: "table-6",
    name: "Table 6 - Work Friends",
    type: "Work",
    shape: "round",
    capacity: 10,
    position: { x: 76, y: 70 },
    assignedGuestIds: ["johan-ek", "lisa-ek", "miles-reed", "sophia-grant"]
  }
];

export const venueLayout: VenueLayout = {
  id: "rosewood-hall-ballroom",
  type: "Reception",
  name: "Rosewood Hall Ballroom",
  capacity: 140,
  objects: [
    { id: "dance-floor", label: "Dance Floor", type: "dance-floor", position: { x: 50, y: 82 }, size: { width: 28, height: 14 } },
    { id: "bar", label: "Bar", type: "bar", position: { x: 9, y: 82 }, size: { width: 14, height: 10 } },
    { id: "stage", label: "Stage / MC", type: "stage", position: { x: 50, y: 7 }, size: { width: 28, height: 8 } },
    { id: "entrance", label: "Guest Entrance", type: "entrance", position: { x: 8, y: 14 }, size: { width: 14, height: 8 } },
    { id: "cake-table", label: "Cake Table", type: "cake", position: { x: 91, y: 18 }, size: { width: 12, height: 8 } },
    { id: "service-path", label: "Catering Service Path", type: "service", position: { x: 91, y: 58 }, size: { width: 10, height: 50 } }
  ]
};

export const timelineItems: TimelineItem[] = [
  {
    id: "guest-arrival",
    time: "2:15 PM",
    title: "Guests arrive at the chapel",
    phase: "Guest Arrival",
    location: "St. James Chapel",
    responsibleRole: "Venue usher team",
    responsiblePerson: "Henry Cole",
    notes: "Ushers guide guests toward reserved family rows and accessible seating.",
    visibility: "everyone"
  },
  {
    id: "prelude",
    time: "2:45 PM",
    title: "Musicians begin the prelude",
    phase: "Ceremony Setup",
    location: "St. James Chapel",
    responsibleRole: "Organist",
    responsiblePerson: "Chapel Organist",
    notes: "Prelude starts as the chapel settles.",
    musicCueId: "music-guest-arrival",
    visibility: "everyone"
  },
  {
    id: "ceremony-begins",
    time: "3:00 PM",
    title: "Ceremony begins",
    phase: "Ceremony",
    location: "St. James Chapel",
    responsibleRole: "Officiant",
    responsiblePerson: "Reverend Thomas Allen",
    notes: "Planner gives the final aisle cue.",
    visibility: "everyone"
  },
  {
    id: "wedding-party-entrance",
    time: "3:03 PM",
    title: "Wedding party entrance",
    phase: "Processional",
    location: "Center aisle",
    responsibleRole: "Wedding planner",
    responsiblePerson: "Olivia Hart",
    notes: "Wedding party enters in pairs and pauses near the front pews.",
    musicCueId: "music-wedding-party",
    visibility: "everyone"
  },
  {
    id: "couple-entrance",
    time: "3:05 PM",
    title: "Couple entrance",
    phase: "Processional",
    location: "Center aisle",
    responsibleRole: "Wedding planner",
    responsiblePerson: "Olivia Hart",
    notes: "Soloist begins after the wedding party reaches the front.",
    musicCueId: "music-couple-entrance",
    visibility: "everyone",
    riskLevel: "medium"
  },
  {
    id: "ring-exchange",
    time: "3:40 PM",
    title: "Ring exchange",
    phase: "Ceremony",
    location: "Altar",
    responsibleRole: "Officiant",
    responsiblePerson: "Reverend Thomas Allen",
    notes: "Ring bearer is seated with immediate family after processional.",
    visibility: "everyone"
  },
  {
    id: "recessional",
    time: "3:55 PM",
    title: "Recessional music",
    phase: "Recessional",
    location: "Center aisle",
    responsibleRole: "DJ / musician",
    responsiblePerson: "Miles Reed",
    notes: "Start immediately after pronouncement.",
    musicCueId: "music-recessional",
    visibility: "everyone",
    riskLevel: "medium"
  },
  {
    id: "group-photos",
    time: "4:10 PM",
    title: "Group photos outside the chapel",
    phase: "Photography",
    location: "Chapel garden",
    responsibleRole: "Photographer",
    responsiblePerson: "Clara Hayes",
    notes: "Family photo list includes immediate family, wedding party, and grandparents.",
    visibility: "everyone",
    riskLevel: "medium",
    durationMinutes: 20
  },
  {
    id: "cocktail-hour",
    time: "5:30 PM",
    title: "Cocktail hour at Rosewood Hall",
    phase: "Cocktail Hour",
    location: "Rosewood Hall terrace",
    responsibleRole: "Venue manager",
    responsiblePerson: "Henry Cole",
    notes: "Bar opens on the terrace and servers pass champagne.",
    visibility: "everyone"
  },
  {
    id: "reception-doors",
    time: "6:00 PM",
    title: "Reception doors open",
    phase: "Reception",
    location: "Rosewood Hall ballroom",
    responsibleRole: "Toastmaster",
    responsiblePerson: "Daniel Brooks",
    notes: "Guests move from terrace to ballroom.",
    musicCueId: "music-reception-entrance",
    visibility: "everyone"
  },
  {
    id: "welcome-toast",
    time: "6:25 PM",
    title: "Welcome toast",
    phase: "Speeches",
    location: "Ballroom",
    responsibleRole: "Toastmaster",
    responsiblePerson: "Daniel Brooks",
    notes: "Short welcome before dinner service begins.",
    speechId: "speech-welcome-toast",
    visibility: "everyone"
  },
  {
    id: "first-course",
    time: "6:45 PM",
    title: "First course is served",
    phase: "Dinner Service",
    location: "Ballroom",
    responsibleRole: "Catering lead",
    responsiblePerson: "Sophia Grant",
    notes: "Catering pauses service during speeches.",
    visibility: "vendor"
  },
  {
    id: "brides-father-speech",
    time: "7:20 PM",
    title: "Speech from the bride's father",
    phase: "Speeches",
    location: "Ballroom",
    responsibleRole: "Toastmaster",
    responsiblePerson: "Daniel Brooks",
    notes: "Scheduled after the first course.",
    speechId: "speech-brides-father",
    visibility: "couple"
  },
  {
    id: "main-course",
    time: "8:15 PM",
    title: "Main course",
    phase: "Dinner Service",
    location: "Ballroom",
    responsibleRole: "Catering lead",
    responsiblePerson: "Sophia Grant",
    notes: "Service path must stay clear along the east wall.",
    visibility: "vendor"
  },
  {
    id: "grooms-sister-speech",
    time: "8:45 PM",
    title: "Groom's sister speech",
    phase: "Speeches",
    location: "Ballroom",
    responsibleRole: "Toastmaster",
    responsiblePerson: "Daniel Brooks",
    notes: "Surprise speech for the couple.",
    speechId: "speech-grooms-sister",
    visibility: "secret",
    riskLevel: "low"
  },
  {
    id: "best-man-speech",
    time: "9:00 PM",
    title: "Best Man Speech",
    phase: "Speeches",
    location: "Ballroom",
    responsibleRole: "Toastmaster",
    responsiblePerson: "Daniel Brooks",
    notes: "Keep under seven minutes and confirm final tone with Toastmaster.",
    speechId: "speech-best-man",
    visibility: "everyone",
    riskLevel: "low"
  },
  {
    id: "friends-song",
    time: "9:15 PM",
    title: "Friends' Song Performance",
    phase: "Speeches",
    location: "Ballroom",
    responsibleRole: "Toastmaster",
    responsiblePerson: "Daniel Brooks",
    notes: "Secret musical performance needs speaker input.",
    speechId: "speech-friends-song",
    visibility: "secret",
    riskLevel: "medium"
  },
  {
    id: "cake-cutting",
    time: "9:30 PM",
    title: "Cake cutting",
    phase: "Cake",
    location: "Cake table",
    responsibleRole: "Wedding planner",
    responsiblePerson: "Olivia Hart",
    notes: "Planner moves the couple to the cake table after surprise performance.",
    visibility: "everyone"
  },
  {
    id: "couple-thank-you",
    time: "9:45 PM",
    title: "Couple thank-you toast",
    phase: "Speeches",
    location: "Ballroom",
    responsibleRole: "Toastmaster",
    responsiblePerson: "Daniel Brooks",
    notes: "Couple thanks families, guests, and vendors.",
    speechId: "speech-couple-thank-you",
    visibility: "everyone"
  },
  {
    id: "first-dance",
    time: "10:00 PM",
    title: "First dance",
    phase: "First Dance",
    location: "Dance floor",
    responsibleRole: "DJ",
    responsiblePerson: "Miles Reed",
    notes: "DJ needs exact timestamp and fade plan.",
    musicCueId: "music-first-dance",
    visibility: "everyone",
    riskLevel: "medium"
  },
  {
    id: "party-begins",
    time: "10:15 PM",
    title: "Party begins",
    phase: "Party",
    location: "Dance floor",
    responsibleRole: "DJ",
    responsiblePerson: "Miles Reed",
    notes: "Open dance floor after first dance and family dances.",
    visibility: "everyone"
  }
];

export const musicCues: MusicCue[] = [
  {
    id: "music-guest-arrival",
    moment: "Guest Arrival",
    songTitle: "Instrumental Prelude",
    artist: "Chapel Organist",
    responsiblePerson: "Organist",
    link: "Private planning link placeholder",
    startCue: "Begin 15 minutes before ceremony",
    backupPlan: "Piano playlist",
    status: "confirmed",
    notes: "Keep volume low enough for ushers to communicate.",
    timelineItemId: "prelude"
  },
  {
    id: "music-wedding-party",
    moment: "Wedding Party Entrance",
    songTitle: "Canon in D",
    artist: "Pachelbel",
    responsiblePerson: "Organist",
    link: "Private planning link placeholder",
    startCue: "Start when chapel doors open",
    backupPlan: "Sheet music printed",
    status: "confirmed",
    notes: "Repeat final section if the entrance runs long.",
    timelineItemId: "wedding-party-entrance"
  },
  {
    id: "music-couple-entrance",
    moment: "Couple Entrance",
    songTitle: "A Thousand Years",
    artist: "Christina Perri",
    responsiblePerson: "Soloist",
    link: "Private planning link placeholder",
    startCue: "Start after wedding party reaches the front",
    backupPlan: "Acoustic instrumental version",
    status: "needs-confirmation",
    notes: "Confirm arrangement length with soloist.",
    timelineItemId: "couple-entrance"
  },
  {
    id: "music-recessional",
    moment: "Recessional",
    songTitle: "Signed, Sealed, Delivered",
    artist: "Stevie Wonder",
    responsiblePerson: "DJ",
    link: "Private planning link placeholder",
    startCue: "Start immediately after pronouncement",
    backupPlan: "Missing",
    status: "needs-backup",
    notes: "DJ should prepare a local backup file.",
    timelineItemId: "recessional"
  },
  {
    id: "music-reception-entrance",
    moment: "Reception Entrance",
    songTitle: "You Make My Dreams",
    artist: "Hall & Oates",
    responsiblePerson: "DJ",
    link: "Private planning link placeholder",
    startCue: "Start when doors open",
    backupPlan: "DJ local file",
    status: "confirmed",
    notes: "Toastmaster introduces couple before the doors open.",
    timelineItemId: "reception-doors"
  },
  {
    id: "music-first-dance",
    moment: "First Dance",
    songTitle: "Can't Help Falling in Love",
    artist: "Elvis Presley",
    responsiblePerson: "DJ",
    link: "Private planning link placeholder",
    startCue: "Missing exact timestamp",
    backupPlan: "DJ local file",
    status: "needs-cue",
    notes: "Confirm start point and fade-out with the couple.",
    timelineItemId: "first-dance"
  }
];

export const speeches: Speech[] = [
  {
    id: "speech-welcome-toast",
    title: "Welcome Toast",
    speakerName: "Daniel Brooks",
    relation: "Toastmaster",
    durationMinutes: 4,
    timing: "6:25 PM",
    visibility: "everyone",
    isSecret: false,
    technicalNeeds: ["Microphone"],
    introPerson: "None",
    notes: "Opens the reception and welcomes guests.",
    timelineItemId: "welcome-toast"
  },
  {
    id: "speech-brides-father",
    title: "Bride's Father Speech",
    speakerName: "Robert Carter",
    relation: "Father of the bride",
    durationMinutes: 8,
    timing: "7:20 PM",
    visibility: "couple",
    isSecret: false,
    technicalNeeds: ["Microphone"],
    introPerson: "Daniel Brooks",
    notes: "Scheduled after the first course.",
    timelineItemId: "brides-father-speech"
  },
  {
    id: "speech-grooms-sister",
    title: "Groom's Sister Speech",
    speakerName: "Amelia Bennett",
    relation: "Sister of the groom",
    durationMinutes: 6,
    timing: "8:45 PM",
    visibility: "secret",
    isSecret: true,
    technicalNeeds: ["Microphone"],
    introPerson: "Daniel Brooks",
    notes: "Surprise speech for the couple.",
    timelineItemId: "grooms-sister-speech"
  },
  {
    id: "speech-best-man",
    title: "Best Man Speech",
    speakerName: "Michael Turner",
    relation: "Best man",
    durationMinutes: 7,
    timing: "9:00 PM",
    visibility: "everyone",
    isSecret: false,
    technicalNeeds: ["Microphone"],
    introPerson: "Daniel Brooks",
    notes: "Keep under 7 minutes.",
    timelineItemId: "best-man-speech"
  },
  {
    id: "speech-friends-song",
    title: "Friends' Song Performance",
    speakerName: "College friends",
    relation: "Friends",
    durationMinutes: 5,
    timing: "9:15 PM",
    visibility: "secret",
    isSecret: true,
    technicalNeeds: ["Microphone", "Speaker input"],
    introPerson: "Daniel Brooks",
    notes: "Surprise musical performance.",
    timelineItemId: "friends-song"
  },
  {
    id: "speech-couple-thank-you",
    title: "Couple Thank-You Toast",
    speakerName: "Emma & James",
    relation: "Couple",
    durationMinutes: 4,
    timing: "9:45 PM",
    visibility: "everyone",
    isSecret: false,
    technicalNeeds: ["Microphone"],
    introPerson: "Daniel Brooks",
    notes: "Before cake cutting.",
    timelineItemId: "couple-thank-you"
  }
];

export const previewPhases: PreviewPhase[] = [
  {
    id: "phase-guest-arrival",
    title: "Guest Arrival",
    timeRange: "2:15 PM - 2:45 PM",
    location: "St. James Chapel",
    summary: "Guests are welcomed, seated, and guided toward family and accessibility rows.",
    involvedPeople: ["Venue usher team", "Henry Cole", "Family members"],
    responsibleRole: "Venue",
    responsiblePerson: "Henry Cole",
    relatedTimelineItemIds: ["guest-arrival", "prelude"]
  },
  {
    id: "phase-prelude",
    title: "Ceremony Prelude",
    timeRange: "2:45 PM - 3:00 PM",
    location: "St. James Chapel",
    summary: "The chapel settles into the ceremony atmosphere as musicians begin.",
    involvedPeople: ["Organist", "Soloist", "Olivia Hart"],
    responsibleRole: "Music",
    responsiblePerson: "Organist",
    musicCueId: "music-guest-arrival",
    relatedTimelineItemIds: ["prelude"]
  },
  {
    id: "phase-processional",
    title: "Processional",
    timeRange: "3:03 PM - 3:07 PM",
    location: "Center aisle",
    summary: "Wedding party and couple enter in a coordinated sequence with live music cues.",
    involvedPeople: ["Wedding party", "Emma Carter", "James Bennett", "Olivia Hart"],
    responsibleRole: "Wedding planner",
    responsiblePerson: "Olivia Hart",
    musicCueId: "music-couple-entrance",
    riskId: "risk-couple-entrance-confirmation",
    relatedTimelineItemIds: ["wedding-party-entrance", "couple-entrance"]
  },
  {
    id: "phase-vows",
    title: "Vows & Ring Exchange",
    timeRange: "3:10 PM - 3:43 PM",
    location: "Altar",
    summary: "The officiant leads the ceremony through readings, vows, and ring exchange.",
    involvedPeople: ["Emma Carter", "James Bennett", "Reverend Thomas Allen"],
    responsibleRole: "Officiant",
    responsiblePerson: "Reverend Thomas Allen",
    relatedTimelineItemIds: ["ceremony-begins", "ring-exchange"]
  },
  {
    id: "phase-recessional",
    title: "Recessional",
    timeRange: "3:55 PM - 4:05 PM",
    location: "Center aisle",
    summary: "The couple exits while music signals the emotional transition into celebration.",
    involvedPeople: ["Couple", "Wedding party", "DJ"],
    responsibleRole: "DJ / musician",
    responsiblePerson: "Miles Reed",
    musicCueId: "music-recessional",
    riskId: "risk-music-backup",
    relatedTimelineItemIds: ["recessional"]
  },
  {
    id: "phase-group-photos",
    title: "Group Photos",
    timeRange: "4:10 PM - 4:30 PM",
    location: "Chapel garden",
    summary: "Family and wedding party portraits are gathered before guests move to cocktail hour.",
    involvedPeople: ["Clara Hayes", "Immediate family", "Wedding party"],
    responsibleRole: "Photographer",
    responsiblePerson: "Clara Hayes",
    riskId: "risk-group-photo-time",
    relatedTimelineItemIds: ["group-photos"]
  },
  {
    id: "phase-cocktail-hour",
    title: "Cocktail Hour",
    timeRange: "5:30 PM - 6:00 PM",
    location: "Rosewood Hall terrace",
    summary: "Guests arrive at Rosewood Hall, receive drinks, and move gradually toward the ballroom.",
    involvedPeople: ["Henry Cole", "Venue staff", "Guests"],
    responsibleRole: "Venue",
    responsiblePerson: "Henry Cole",
    relatedTimelineItemIds: ["cocktail-hour"]
  },
  {
    id: "phase-reception-entrance",
    title: "Reception Entrance",
    timeRange: "6:00 PM - 6:25 PM",
    location: "Rosewood Hall ballroom",
    summary: "Doors open, the couple is announced, and the room shifts into dinner service.",
    involvedPeople: ["Daniel Brooks", "Miles Reed", "Emma & James"],
    responsibleRole: "Toastmaster / MC",
    responsiblePerson: "Daniel Brooks",
    musicCueId: "music-reception-entrance",
    relatedTimelineItemIds: ["reception-doors", "welcome-toast"]
  },
  {
    id: "phase-dinner",
    title: "Dinner Service",
    timeRange: "6:45 PM - 8:30 PM",
    location: "Ballroom",
    summary: "Courses are served around speeches, allergies, and service path timing.",
    involvedPeople: ["Sophia Grant", "Daniel Brooks", "Venue team"],
    responsibleRole: "Catering",
    responsiblePerson: "Sophia Grant",
    riskId: "risk-catering-allergy",
    relatedTimelineItemIds: ["first-course", "main-course"]
  },
  {
    id: "phase-speeches",
    title: "Speeches",
    timeRange: "6:25 PM - 9:45 PM",
    location: "Ballroom",
    summary: "Toastmaster manages visible and secret program moments while protecting dinner flow.",
    involvedPeople: ["Daniel Brooks", "Speakers", "Miles Reed"],
    responsibleRole: "Toastmaster / MC",
    responsiblePerson: "Daniel Brooks",
    riskId: "risk-speech-length",
    relatedTimelineItemIds: ["welcome-toast", "brides-father-speech", "grooms-sister-speech", "best-man-speech", "friends-song", "couple-thank-you"]
  },
  {
    id: "phase-cake",
    title: "Cake Cutting",
    timeRange: "9:30 PM - 9:40 PM",
    location: "Cake table",
    summary: "Planner gathers the couple and photographer for the cake moment.",
    involvedPeople: ["Olivia Hart", "Clara Hayes", "Emma & James"],
    responsibleRole: "Wedding planner",
    responsiblePerson: "Olivia Hart",
    relatedTimelineItemIds: ["cake-cutting"]
  },
  {
    id: "phase-first-dance",
    title: "First Dance",
    timeRange: "10:00 PM - 10:15 PM",
    location: "Dance floor",
    summary: "The first dance opens the evening party and needs a precise music cue.",
    involvedPeople: ["Emma & James", "Miles Reed", "Clara Hayes"],
    responsibleRole: "DJ",
    responsiblePerson: "Miles Reed",
    musicCueId: "music-first-dance",
    riskId: "risk-music-start-cue",
    relatedTimelineItemIds: ["first-dance"]
  },
  {
    id: "phase-party",
    title: "Party",
    timeRange: "10:15 PM onward",
    location: "Dance floor",
    summary: "DJ opens the floor and the production map shifts into celebration mode.",
    involvedPeople: ["Miles Reed", "Guests", "Venue team"],
    responsibleRole: "DJ",
    responsiblePerson: "Miles Reed",
    relatedTimelineItemIds: ["party-begins"]
  }
];

export const exportTypes: ExportType[] = [
  {
    id: "full-run-of-show",
    title: "Full Wedding Run of Show",
    description: "The complete production timeline for every major wedding-day moment.",
    contactPerson: "Olivia Hart",
    timelineItemIds: timelineItems.map((item) => item.id),
    warningIds: ["risk-group-photo-time", "risk-speech-length", "risk-music-backup", "risk-music-start-cue"]
  },
  {
    id: "toastmaster-brief",
    title: "Toastmaster Brief",
    description: "Reception timing, speeches, secret layers, microphone cues, and program risks.",
    contactPerson: "Daniel Brooks",
    timelineItemIds: ["reception-doors", "welcome-toast", "brides-father-speech", "grooms-sister-speech", "best-man-speech", "friends-song", "cake-cutting", "couple-thank-you"],
    warningIds: ["risk-speech-length", "risk-secret-technical"]
  },
  {
    id: "photographer-brief",
    title: "Photographer Brief",
    description: "Ceremony positions, group photo timing, key people, chapel exit, and golden hour reminders.",
    contactPerson: "Clara Hayes",
    timelineItemIds: ["ceremony-begins", "recessional", "group-photos", "cake-cutting", "first-dance"],
    warningIds: ["risk-group-photo-time"]
  },
  {
    id: "dj-cue-sheet",
    title: "DJ / Music Cue Sheet",
    description: "All music moments, start cues, backup plans, status, and related timeline items.",
    contactPerson: "Miles Reed",
    timelineItemIds: ["prelude", "wedding-party-entrance", "couple-entrance", "recessional", "reception-doors", "first-dance", "party-begins"],
    warningIds: ["risk-music-backup", "risk-music-start-cue", "risk-couple-entrance-confirmation"]
  },
  {
    id: "catering-sheet",
    title: "Catering Timing & Allergy Sheet",
    description: "Dinner timing, allergy details, meal preferences, child meals, and service interruptions.",
    contactPerson: "Sophia Grant",
    timelineItemIds: ["first-course", "brides-father-speech", "main-course", "friends-song"],
    warningIds: ["risk-catering-allergy", "risk-vegan-meal", "risk-child-meal"]
  },
  {
    id: "ceremony-plan",
    title: "Ceremony Plan",
    description: "Chapel layout, ceremony order, processional cues, music moments, and photography positions.",
    contactPerson: "Reverend Thomas Allen",
    timelineItemIds: ["guest-arrival", "prelude", "ceremony-begins", "wedding-party-entrance", "couple-entrance", "ring-exchange", "recessional"],
    warningIds: ["risk-music-backup", "risk-balcony-approval"]
  },
  {
    id: "reception-seating-plan",
    title: "Reception Seating Plan",
    description: "Table assignments, guest notes, accessibility needs, meal preferences, and seating conflicts.",
    contactPerson: "Olivia Hart",
    timelineItemIds: ["cocktail-hour", "reception-doors", "first-course", "main-course"],
    warningIds: ["risk-catering-allergy", "risk-accessibility", "risk-seating-conflict"]
  },
  {
    id: "venue-setup-brief",
    title: "Venue Setup Brief",
    description: "Room layout, service path, bar, dance floor, cake table, accessibility route, and setup notes.",
    contactPerson: "Henry Cole",
    timelineItemIds: ["guest-arrival", "cocktail-hour", "reception-doors", "first-course", "main-course", "party-begins"],
    warningIds: ["risk-accessibility", "risk-service-path"]
  }
];
